---
- name: add unison ppa
  become: yes
  apt_repository:
    repo: 'ppa:john-freeman/unison'

- name: install unison
  become: yes
  apt:
    name: unison
    state: present

- name: write unison systemd configration
  become: yes
  template:
    src: unison.service
    dest: /etc/systemd/system/unison.service

- name: create vagrant .unison directory
  become: yes
  file:
    path: /home/vagrant/.unison/
    state: directory
    owner: vagrant
    group: vagrant
    mode: 'u=rwx,go=rx'

- name: write unison vagrant profile
  become: yes
  template:
    src: vagrant.prf
    dest: /home/vagrant/.unison/vagrant.prf
    owner: vagrant
    group: vagrant
    mode: 'u=rw,go=r'

- name: sync missing files from host to client
  become: yes
  become_user: vagrant
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -nodeletion=/home/vagrant
    -noupdate=/home/vagrant
    -prefer=/vagrant/home
    -force=/vagrant/home
    -ignorearchives
    -logfile=/home/vagrant/.unison/init1.log
    &> /home/vagrant/.unison/init1.out
  register: command_result
  failed_when: command_result.rc > 1

- name: create missing includeDirectories
  become: yes
  file:
    path: "/home/vagrant/{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: 'u=rwx,go=rx'
  with_items: "{{ unison_include_directories }}"

- name: create missing includeFiles
  become: yes
  copy:
    content: ''
    dest: "/home/vagrant/{{ item }}"
    force: no
    owner: vagrant
    group: vagrant
    mode: 'u=rw,go=r'
  with_items: "{{ unison_include_files }}"

- name: sync missing files from client to host
  become: yes
  become_user: vagrant
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -nodeletion=/vagrant/home
    -noupdate=/vagrant/home
    -prefer=/home/vagrant
    -force=/home/vagrant
    -ignorearchives
    -logfile=/home/vagrant/.unison/init2.log
    &> /home/vagrant/.unison/init2.out
  register: command_result
  failed_when: command_result.rc > 1

- name: sync file changes from host to client
  become: yes
  become_user: vagrant
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -prefer=/vagrant/home
    -force=/vagrant/home
    -nodeletion=/home/vagrant
    -ignorearchives
    -logfile=/home/vagrant/.unison/init3.log
    &> /home/vagrant/.unison/init3.out
  register: command_result
  failed_when: command_result.rc > 1

- name: delete unison archives
  become: yes
  command: >
    /usr/bin/find
    /home/vagrant/.unison
    -regextype posix-extended
    -regex ".*/(ar|fp)[0-9a-f]{32}"
    -delete

- name: recreate unison archives
  become: yes
  become_user: vagrant
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -logfile=/home/vagrant/.unison/init4.log
    &> /home/vagrant/.unison/init4.out
  register: command_result
  failed_when: command_result.rc > 1

- name: add unison service to default run level and start
  become: yes
  tags:
    # Add init-system tag so we can skip this task when running in Docker
    - init-system
  # Since Vagrant shares are mounted/unmounted outside the systemd lifecycle
  # we can't auto-start/auto-stop the service using systemd.
  service:
    name: unison
    enabled: no
    state: stopped
