---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-unison-01
    image: ubuntu:16.04

provisioner:
  name: ansible
  options:
    # Docker doesn't suuport the init system so we skip the service registration
    # by adding --skip-tags init-system when running ansible-playbook
    skip-tags: init-system
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
